// Cloud copy is generated by scripts/build-egg-config-identities.js.
const records = require('./eggConfigIdentities');
const speciesForms = require('./eggSpeciesForms');

function get(id) {
  const number = Number(id);
  return Number.isSafeInteger(number) && number > 0 ? records[number] || null : null;
}

function normalize(input) {
  if (!input || typeof input !== 'object' || Array.isArray(input)) return input;
  const row = get(input.petConfId);
  if (!row) {
    const type = Number(input.preciousEggType);
    const form = formName(input.petConfId);
    return { ...input,
      ...(form ? { petFormName: form } : {}),
      ...(type === 2 ? { isShiny: true, isOrdinary: false } : {}),
      ...(type === 6 || type === 7 ? { isColorful: true, isOrdinary: false } : {}) };
  }
  const [name, speciesPetId, configuredType] = row;
  // The source only identifies 古钟蛇 at species level. Do not erase a
  // separately captured appearance when its shared config cannot distinguish it.
  const captured = String(input.petFormName || input.petDisplayName || '');
  const resolvedForm = name === '古钟蛇' && /^古钟蛇_.+/.test(captured) ? captured : name;
  const preciousEggType = configuredType > 0 ? configuredType : (input.preciousEggType ?? configuredType);
  const hadShinyName = /^异色/.test(String(input.petName || input.petDisplayName || ''));
  return {
    ...input,
    petName: name,
    petDisplayName: resolvedForm,
    petFormName: resolvedForm,
    speciesPetId,
    preciousEggType,
    isShiny: Number(preciousEggType) === 2 || input.isShiny === true || hadShinyName,
    isColorful: preciousEggType === 6 || preciousEggType === 7 || input.isColorful === true,
    ...(preciousEggType > 0 ? { isOrdinary: false } : {}),
    formResolution: 'verified-egg-config',
    recognized: true,
    unrecognized: false,
    unrecognizedReason: ''
  };
}

function formName(id) {
  const row = get(id);
  if (row) return row[0];
  const number = Number(id);
  if (!Number.isSafeInteger(number) || number <= 0) return '';
  const digits = String(number).length;
  if (digits !== 7 && digits !== 8) return '';
  const species = Math.floor(number / (digits === 8 ? 10000 : 1000));
  return speciesForms[species] || '';
}

module.exports = { get, normalize, records, formName };
